name: "Build"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.git/**'
      - 'LICENSE'
      - 'README'
      - 'changelog.txt'
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build
        uses: kaespi/action-web-ext@kg_artifcat_customization
        with:
          cmd: build
          source: src

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: 'SRF.ch Firefox extension'
          path: ${{ steps.web-ext-build.outputs.target }}
